blank_issues_enabled: false
contact_links:
  - name: Ask a question or share ideas
    url: https://github.com/watermeloncorp/watermelon-platform/discussions
    about: Please ask and answer questions here!
  - name: Report a security vulnerability
    url: https://github.com/watermeloncorp/watermelon-platform/security/advisories/new
    about: Please report security vulnerabilities privately using the GitHub Security Advisory.
